services:
  react-app:
    image: react-app:latest
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "80:80"
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html